### ISSUE TITLE
Rotation in the items?

### ISSUE THREAD

**Issue by ghost** [Oscar-Oliveira/BPP-3D-Viewer#4]
I have been testing your project. Excellent work, it works as expected, but I have seen that it does not rotate the items.

I have reviewed the scheme, and the only thing related is a flag but it really does not do anything. Could you give more explanation? What is this used for?

> "r": { "description": "Rotated flag (0 -  false)","type": "number" }

**Comment by Oscar-Oliveira** [comment]
Hi, it is only a flag that identifies if the item was placed rotated. When I export a 3D cutting plan, it serves  to observe which items were rotated by the algorithms. 

BR
Oscar

**Comment by ghost** [comment]
OK, I understand. So thank you very much!
